In [6]:
import pandas as pd
import numpy as np

churn = pd.read_csv(
    "../data/processed/churn_clean.csv"
)

marketing = pd.read_csv(
    "../data/processed/marketing_clean.csv"
)

engagement = pd.read_csv(
    "../data/processed/engagement_clean.csv"
)

retail = pd.read_csv(
    "../data/processed/retail_clean.csv"
)

merchant = pd.read_csv(
    "../data/processed/merchant_clean.csv"
)

In [7]:
print(churn.columns)
print()

print(marketing.columns)
print()

print(engagement.columns)

Index(['clientnum', 'attrition_flag', 'customer_age', 'gender',
       'dependent_count', 'education_level', 'marital_status',
       'income_category', 'card_category', 'months_on_book',
       'total_relationship_count', 'months_inactive_12_mon',
       'contacts_count_12_mon', 'credit_limit', 'total_revolving_bal',
       'avg_open_to_buy', 'total_amt_chng_q4_q1', 'total_trans_amt',
       'total_trans_ct', 'total_ct_chng_q4_q1', 'avg_utilization_ratio'],
      dtype='str')

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response'],
      dtype='str')

Index(['customer_id', 'app_logins', 'email_clicks', 'support_calls',
       'complaints', 'offer_acceptance'],
      dtype='str')

In [8]:
churn_df = churn[[

'clientnum',

'customer_age',

'gender',

'credit_limit',

'total_trans_amt',

'total_trans_ct',

'avg_utilization_ratio',

'attrition_flag'

]]

In [9]:
churn_df.columns=[

'customer_id',

'age',

'gender',

'credit_limit',

'total_spend',

'transaction_count',

'utilization',

'churn_flag'

]

In [10]:
marketing_df = marketing[[

'id',

'income',

'education',

'response'

]]

In [11]:
marketing_df.columns=[

'customer_id',

'income',

'education',

'campaign_response'

]

In [12]:
engagement_df = engagement.copy()


engagement_df['engagement_score']=(

engagement_df['app_logins']*0.4+

engagement_df['email_clicks']*0.3+

engagement_df['offer_acceptance']*20-

engagement_df['complaints']*5

)


engagement_df = engagement_df[[

'customer_id',

'engagement_score',

'offer_acceptance'

]]

In [14]:
customer360 = churn_df.merge(

    engagement_df,

    on='customer_id',

    how='left'

)

In [15]:
customer360.shape

(10127, 10)

In [16]:
customer360.isnull().sum()

customer_id          0
age                  0
gender               0
credit_limit         0
total_spend          0
transaction_count    0
utilization          0
churn_flag           0
engagement_score     0
offer_acceptance     0
dtype: int64

In [17]:
customer360.fillna(

0,

inplace=True

)

,customer_id,age,gender,credit_limit,total_spend,transaction_count,utilization,churn_flag,engagement_score,offer_acceptance
0,768805383,45,M,12691.0,1144,42,0.061,Existing Customer,7.2,0
1,818770008,49,F,8256.0,1291,33,0.105,Existing Customer,24.5,1
2,713982108,51,M,3418.0,1887,20,0.000,Existing Customer,21.6,0
3,769911858,40,F,3313.0,1171,20,0.760,Existing Customer,57.9,1
4,709106358,40,M,4716.0,816,28,0.000,Existing Customer,11.5,0
...,...,...,...,...,...,...,...,...,...,...
10122,772366833,50,M,4003.0,15476,117,0.462,Existing Customer,28.0,1
10123,710638233,41,M,4277.0,8764,69,0.511,Attrited Customer,13.8,0
10124,716506083,44,F,5409.0,10291,60,0.000,Attrited Customer,31.4,1
10125,717406983,30,M,5281.0,8395,62,0.000,Attrited Customer,20.0,0
10126,714337233,43,F,10388.0,10294,61,0.189,Attrited Customer,18.1,1

In [18]:
customer360.head()

,customer_id,age,gender,credit_limit,total_spend,transaction_count,utilization,churn_flag,engagement_score,offer_acceptance
0,768805383,45,M,12691.0,1144,42,0.061,Existing Customer,7.2,0
1,818770008,49,F,8256.0,1291,33,0.105,Existing Customer,24.5,1
2,713982108,51,M,3418.0,1887,20,0.000,Existing Customer,21.6,0
3,769911858,40,F,3313.0,1171,20,0.760,Existing Customer,57.9,1
4,709106358,40,M,4716.0,816,28,0.000,Existing Customer,11.5,0

In [19]:
customer360.to_csv(

'../data/customer360.csv',

index=False

)